/**
 * Git operations and models for commits, tags, refs, logging, staging, and diff operations.
 *
 * @module @hyperfrontend/versioning/git
 */
export type { GitClient, GitClientConfig } from './factory'
export type {
  CreateGitCommitOptions,
  GitCommit,
  CreateGitRefOptions,
  GitRef,
  GitRefType,
  CreateAnnotatedTagOptions,
  CreateLightweightTagOptions,
  GitTag,
  GitTagType,
} from './models'
export {
  buildTagName,
  compareTagsByVersion,
  createAnnotatedTag,
  createGitCommit,
  createGitRef,
  createLightweightTag,
  extractPackageFromTag,
  extractScope,
  extractType,
  extractVersionFromTag,
  filterRefsByRemote,
  filterRefsByType,
  getRemote,
  getShortHash,
  isAnnotatedTag,
  isBranchRef,
  isHeadRef,
  isLightweightTag,
  isMergeCommit,
  isRemoteRef,
  isRootCommit,
  isSameCommit,
  isTagRef,
  buildRefName,
  compareRefsByName,
} from './models'
export type {
  GitLogOptions,
  GitTagOptions,
  ListTagsOptions,
  CreateTagOptions,
  GitCommitOptions,
  CreateCommitOptions,
  StageOptions,
  DiscardChangesOptions,
  GitStatusOptions,
  FileStatus,
  FileStatusEntry,
  RepositoryStatus,
  GitOperationStateReason,
  GitOperationState,
  GitOperationStateOptions,
  FileChangeStatus,
  FileChange,
  DiffOptions,
  GitCommitWithFiles,
} from './operations'
export {
  amendCommit,
  amendCommitNoEdit,
  commit,
  commitExists,
  commitReachableFromHead,
  createEmptyCommit,
  createTag,
  DEFAULT_COMMIT_OPTIONS,
  DEFAULT_DIFF_OPTIONS,
  DEFAULT_LOG_OPTIONS,
  DEFAULT_OPERATION_STATE_OPTIONS,
  DEFAULT_STATUS_OPTIONS,
  DEFAULT_TAG_OPTIONS,
  deleteTag,
  discardAllChanges,
  discardChanges,
  escapeAuthor,
  escapeFilePath,
  escapeGitArg,
  escapeGitMessage,
  escapeGitPath,
  escapeGitRef,
  escapeGitTagPattern,
  getAheadCount,
  getBehindCount,
  getChangedFilesBetween,
  getChangedFilesBetweenWithStatus,
  getCommit,
  getCommitLog,
  getCommitsBetween,
  getCommitsSince,
  getCommitWithFiles,
  getCurrentBranch,
  getHead,
  getHeadHash,
  getHeadShortHash,
  getLatestTag,
  getModifiedFiles,
  getOperationState,
  getRepositoryRoot,
  getStagedFiles,
  getStatus,
  getTag,
  getTags,
  getTagsForPackage,
  getUntrackedFiles,
  hasConflicts,
  hasStagedChanges,
  hasUnstagedChanges,
  hasUntrackedFiles,
  isClean,
  isGitRepository,
  isOperationInProgress,
  needsPull,
  needsPush,
  pushTag,
  stage,
  stageAll,
  tagExists,
  unstage,
} from './operations'
export { createGitClient, DEFAULT_GIT_CLIENT_CONFIG } from './factory'
