export { ACTION_TYPES } from '../types/action'

/**
 * Convenience exports for individual action types
 * Accessing through ACTION_TYPES.* to avoid destructuring issues
 */
import { ACTION_TYPES as _ACTION_TYPES } from '../types/action'

export const INVALID_REQUEST = _ACTION_TYPES.INVALID_REQUEST
export const REQUEST_CONNECTION = _ACTION_TYPES.REQUEST_CONNECTION
export const CANCEL_CONNECTION = _ACTION_TYPES.CANCEL_CONNECTION
export const CANCEL_CONNECTION_ACKNOWLEDGED = _ACTION_TYPES.CANCEL_CONNECTION_ACKNOWLEDGED
export const ACCEPT_CONNECTION = _ACTION_TYPES.ACCEPT_CONNECTION
export const DENY_CONNECTION = _ACTION_TYPES.DENY_CONNECTION
export const CLOSE_CONNECTION = _ACTION_TYPES.CLOSE_CONNECTION
export const CLOSE_CONNECTION_ACKNOWLEDGED = _ACTION_TYPES.CLOSE_CONNECTION_ACKNOWLEDGED
export const DESTROY_CONNECTION = _ACTION_TYPES.DESTROY_CONNECTION
export const OPEN_CONNECTION = _ACTION_TYPES.OPEN_CONNECTION
export const NEW_MESSAGE = _ACTION_TYPES.NEW_MESSAGE
