/**
 * Comprehensive Keep-a-Changelog module with parsing, serialization, comparison, and operations.
 *
 * @module @hyperfrontend/versioning/changelog
 */
export type {
  Changelog,
  ChangelogEntry,
  ChangelogFormat,
  ChangelogHeader,
  ChangelogItem,
  ChangelogLink,
  ChangelogMetadata,
  ChangelogSection,
  ChangelogSectionType,
  CommitRef,
  CompatibilityResult,
  IssueRef,
  SchemaDifference,
} from './models'
export {
  changelogSchema,
  checkSchemaCompatibility,
  createChangelog,
  createChangelogEntry,
  createChangelogItem,
  createChangelogLink,
  createChangelogSection,
  createCommitRef,
  createEmptyChangelog,
  createIssueRef,
  createUnreleasedEntry,
  getShortHash,
  getSectionType,
  SECTION_HEADINGS,
  SECTION_TYPE_MAP,
  validateChangelog,
} from './models'
export type { Token, TokenType } from './parse'
export { parseChangelog, parseCommitRefs, parseIssueRefs, parseScopeFromItem, parseVersionFromHeading, tokenize } from './parse'
export type { JsonSerializeOptions, SerializeOptions } from './serialize'
export {
  createSpacing,
  DEFAULT_SERIALIZE_OPTIONS,
  formatLink,
  getListMarker,
  getSectionHeading,
  resolveOptions,
  serializeChangelog,
  serializeChangelogToJson,
  toJsonObject,
} from './serialize'
export type { ChangelogDiff, DiffStats, EntryDiff, ItemDiff, PropertyDiff, SectionDiff } from './compare'
export {
  diffChangelogs,
  diffEntries,
  getEntryByVersion,
  hasVersion,
  haveSameVersions,
  isChangelogEqual,
  isCommitRefEqual,
  isEntryEqual,
  isHeaderEqual,
  isIssueRefEqual,
  isItemEqual,
  isLinkEqual,
  isMetadataEqual,
  isSectionEqual,
  summarizeDiff,
} from './compare'
export type {
  AddEntryOptions,
  EntryPredicate,
  EntryTransformer,
  ItemPredicate,
  ItemTransformer,
  MergeOptions,
  MergeResult,
  MergeStats,
  MergeStrategy,
  RemoveEntryOptions,
  RemoveSectionOptions,
  SectionPredicate,
  SectionTransformer,
} from './operations'
export {
  addEntry,
  addItemToEntry,
  addUnreleasedEntry,
  appendChangelog,
  cloneChangelog,
  combineChangelogs,
  compact,
  deduplicateItems,
  DEFAULT_MERGE_OPTIONS,
  excludeByScope,
  filterBreakingChanges,
  filterByDateRange,
  filterByScope,
  filterByVersionRange,
  filterEntries,
  filterFromVersion,
  filterItems,
  filterRecentEntries,
  filterSections,
  filterSectionTypes,
  filterToVersion,
  filterVersionRange,
  mergeChangelogs,
  normalizeSectionHeadings,
  releaseUnreleased,
  removeEmptyEntries,
  removeEmptySections,
  removeEntries,
  removeEntry,
  removeItem,
  removeSection,
  removeUnreleased,
  reverseEntries,
  sortEntries,
  sortEntriesByDate,
  sortSections,
  stripMetadata,
  transformEntries,
  transformItems,
  transformSections,
  updateEntry,
  updateHeader,
  updateMetadata,
} from './operations'
