export { createRegistry } from './factory'
export type { ChannelRegistry } from './factory'
export { add } from './add'
export { remove } from './remove'
export { getByWindow } from './get-by-window'
export { getById } from './get-by-id'
export { getByName } from './get-by-name'
export { getAll } from './get-all'
export { clear } from './clear'
