export type { RegistryType } from './factory'
export type { Registry, RegistryConfig } from './models'
export type { PackageInfo } from './models'
export type { Maintainer, VersionInfo } from './models'
export { createPackageInfo, createVersionInfo } from './models'
export type { Cache, CacheEntry } from './npm'
export { createCache, createNpmRegistry, escapePackageName, escapeVersion } from './npm'
export { createRegistry } from './factory'
