name: lib-logging

on:
  push:
    branches: [main]
    paths:
      - 'libs/logging/**'
      - '.github/workflows/ci-lib-logging.yml'
      - '.github/workflows/_lib-ci.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-lib-logging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_lib-ci.yml
    with:
      project-name: lib-logging
      coverage-path: ./coverage/libs/logging/lcov.info
      coverage-flag: logging
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
