name: lib-network-protocol

on:
  push:
    branches: [main]
    paths:
      - 'libs/network-protocol/**'
      - '.github/workflows/ci-lib-network-protocol.yml'
      - '.github/workflows/_lib-ci.yml'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-lib-network-protocol-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_lib-ci.yml
    with:
      project-name: lib-network-protocol
      coverage-path: ./coverage/libs/network-protocol/lcov.info
      coverage-flag: network-protocol
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
